# SAM CLI configuration file
# Documentation: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

version = 0.1

[default]
[default.global.parameters]
stack_name = "serverless-demo"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "serverless-demo"
region = "us-east-1"
image_repositories = []
parameter_overrides = [
    "Environment=dev",
    "EnableDetailedMonitoring=true"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Production environment configuration
[production]
[production.deploy.parameters]
stack_name = "serverless-demo-prod"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "serverless-demo-prod"
region = "us-east-1"
parameter_overrides = [
    "Environment=prod",
    "EnableDetailedMonitoring=true",
    "TableName=Orders"
]

# Staging environment configuration  
[staging]
[staging.deploy.parameters]
stack_name = "serverless-demo-staging"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "serverless-demo-staging"
region = "us-east-1"
parameter_overrides = [
    "Environment=staging",
    "EnableDetailedMonitoring=true",
    "TableName=Orders"
]
